// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpmtW4i9jbheXajWqg1LabcOj4pk7h2sM',
    appId: '1:334368685850:web:9045303d7f8ca113aaf6a3',
    messagingSenderId: '334368685850',
    projectId: 'manifest-pulsar-362508',
    authDomain: 'manifest-pulsar-362508.firebaseapp.com',
    storageBucket: 'manifest-pulsar-362508.appspot.com',
    measurementId: 'G-GPPE8YZ8VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypSngtp-Sah621cDvLL0r5jiHaNS8ZIw',
    appId: '1:334368685850:android:b1f4f2b55962eb36aaf6a3',
    messagingSenderId: '334368685850',
    projectId: 'manifest-pulsar-362508',
    storageBucket: 'manifest-pulsar-362508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG8_6L02cVhVJMNgy34226wQPVNBhXy-M',
    appId: '1:334368685850:ios:293266623810d6c3aaf6a3',
    messagingSenderId: '334368685850',
    projectId: 'manifest-pulsar-362508',
    storageBucket: 'manifest-pulsar-362508.appspot.com',
    iosBundleId: 'com.example.firebaseAuthLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG8_6L02cVhVJMNgy34226wQPVNBhXy-M',
    appId: '1:334368685850:ios:fc84ec79b2146905aaf6a3',
    messagingSenderId: '334368685850',
    projectId: 'manifest-pulsar-362508',
    storageBucket: 'manifest-pulsar-362508.appspot.com',
    iosBundleId: 'com.example.firebaseAuthLogin.RunnerTests',
  );
}
